site_name: Torch.js - Documentation

pages:
    - Home: 'index.md'
    - Games: 'games.md'
    - Sprites:
        - 'Sprites': 'sprite/sprites.md'
        - 'Shapes': 'sprite/shapes/shapes.md'
    - Utilities:
        - 'Utilities': 'util/utilities.md'
        - 'String': 'util/string.md'
